title: cambridge-ceu
author: Account names
description: Software, documentation, news
baseurl: /_posts/ 
url: https://github.com/cambridge-ceu

twitter:
  username: CAMBRIDGE_CEU

social:
  name: cambridge-ceu
  links:
    - https://github.com/cambridge-ceu
    - https://twitter.com/CAMBRIDGE_CEU
    - https://www.youtube.com/channel/UCeS9CPB2_QGcBsnORnNQyjQ

logo: /assets/images/logo.png

plugins:
  - bundler/graph
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-youtube
  - jemoji

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
  - _pages/internal.md
  - _pages/public.md
  - _pages/github.md
  - _pages/twitter.md
  - _pages/youtube.md
  - _pages/posts.md
  - _pages/about.md

include:
    - _pages

footer_icons:
- username: cambridge-ceu
  url: https://github.com/cambridge-ceu
  icon: icon-github.svg
- username: CAMBRIDGE_CEU
  url: https://twitter.com/CAMBRIDGE_CEU
  icon: icon-twitter.svg
- username: "Cambridge Uni: Cardiovascular Epidemiology Unit"
  url: https://www.youtube.com/channel/UCeS9CPB2_QGcBsnORnNQyjQ
  icon: icon-youtube.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
