# frozen_string_literal: true

source "https://rubygems.org"
gemspec

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "html-proofer", "~> 3.19.3"
  gem "jekyll-sass-converter", "~> 1.5.2"
  gem "jekyll-sitemap", "~> 1.4.0"
  gem "jemoji", "~> 0.12.0"
  gem "rake", "~> 13.0.6"
end
